name: CI

on:
  push:
    branches: [main, staging, trying]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        include:
          # Minimum supported rust version (MSRV)
          - name: MSRV
            rust: 1.53.0

    name: "build (${{ matrix.name || matrix.rust }})"

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: rustfmt
        run: cargo fmt -- --check

      - name: build
        run: cargo xtask ci
